// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVLe7JrsbbQwoOuOQ5LHMceZfIP5paEM0',
    appId: '1:541079898879:web:c8f9f951bbbc3fd294daca',
    messagingSenderId: '541079898879',
    projectId: 'emmieai-47d67',
    authDomain: 'emmieai-47d67.firebaseapp.com',
    storageBucket: 'emmieai-47d67.appspot.com',
    measurementId: 'G-YJ81YSWS7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5vECt-eBL7sQi-ARRe37-05NwcAVVgcQ',
    appId: '1:541079898879:android:ac59312f0e8d32fb94daca',
    messagingSenderId: '541079898879',
    projectId: 'emmieai-47d67',
    storageBucket: 'emmieai-47d67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGNztjxCJ6eGmBVIhtLo9Wo2k_j_ILuu4',
    appId: '1:541079898879:ios:4dc28d853e1d80e794daca',
    messagingSenderId: '541079898879',
    projectId: 'emmieai-47d67',
    storageBucket: 'emmieai-47d67.appspot.com',
    iosBundleId: 'com.example.emmieAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGNztjxCJ6eGmBVIhtLo9Wo2k_j_ILuu4',
    appId: '1:541079898879:ios:4dc28d853e1d80e794daca',
    messagingSenderId: '541079898879',
    projectId: 'emmieai-47d67',
    storageBucket: 'emmieai-47d67.appspot.com',
    iosBundleId: 'com.example.emmieAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVLe7JrsbbQwoOuOQ5LHMceZfIP5paEM0',
    appId: '1:541079898879:web:492946fdc79f3c3994daca',
    messagingSenderId: '541079898879',
    projectId: 'emmieai-47d67',
    authDomain: 'emmieai-47d67.firebaseapp.com',
    storageBucket: 'emmieai-47d67.appspot.com',
    measurementId: 'G-NX4M244B80',
  );
}
